autoCorrect: true
failFast: false

test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
  exclude-rule-sets:
    - 'comments'
  exclude-rules:
    - 'NamingRules'
    - 'WildcardImport'
    - 'MagicNumber'
    - 'MaxLineLength'
    - 'LateinitUsage'
    - 'StringLiteralDuplication'
    - 'SpreadOperator'
    - 'TooManyFunctions'

build:
  warningThreshold: 0
  failThreshold: 0
  weights:
    complexity: 1
    style: 1
    empty-blocks: 2
    exceptions: 2
    potential-bugs: 2
    performance: 1

processors:
  active: true
  exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

output-reports:
  active: true
  exclude:
  #  - 'PlainOutputReport'
  #  - 'XmlOutputReport'

comments:
  active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  LongParameterList:
    active: true
    threshold: 7
    ignoreDefaultParameters: true
  LongMethod:
    active: false
    threshold: 20
  LargeClass:
    active: false
    threshold: 150
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: true
  ComplexMethod:
    active: false
    threshold: 10
  StringLiteralDuplication:
    active: true
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  MethodOverloading:
    active: true
    threshold: 5
  NestedBlockDepth:
    active: true
    threshold: 3
  TooManyFunctions:
    active: false
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
  ComplexCondition:
    active: true
    threshold: 3
  LabeledExpression:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptions:
     - ArrayIndexOutOfBoundsException
     - Error
     - Exception
     - IllegalMonitorStateException
     - NullPointerException
     - IndexOutOfBoundsException
     - RuntimeException
     - Throwable
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: 'toString,hashCode,equals,finalize'
  TooGenericExceptionThrown:
    active: true
    exceptions:
     - Error
     - Exception
     - Throwable
     - RuntimeException
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: true
  InstanceOfCheckForException:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  RethrowCaughtException:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  SwallowedException:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  UselessPostfixExpression:
    active: true
  InvalidRange:
    active: true
  WrongEqualsTypeParameter:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: ""
    ignoreOnClassesPattern: ""
  UnconditionalJumpStatementInLoop:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: false

style:
  active: true
  CollapsibleIfStatements:
    active: true
  ReturnCount:
    active: false
    max: 2
    excludedFunctions: "equals"
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*'
  MaxLineLength:
    active: true
    maxLineLength: 130
    excludePackageStatements: true
    excludeImportStatements: true
  EqualsNullCall:
    active: false
  ForbiddenComment:
    active: true
    values: 'TODO:,FIXME:,STOPSHIP:'

  ForbiddenImport:
    active: false
    imports: ''
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'
  SpacingBetweenPackageAndImports:
    active: false
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  MemberNameEqualsClassName:
    active: true
    ignoreOverriddenFunction: true
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
  VariableMinLength:
    active: false
    minimumVariableNameLength: 1
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 64
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z\d]*'
    privatePropertyPattern: '(_)?[a-z][A-Za-z0-9]*'
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z0-9_$]*$'
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  ForbiddenClassName:
    active: false
    forbiddenName: ''
  SafeCast:
    active: true
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryParentheses:
    active: false
  UnnecessaryInheritance:
    active: false
  UtilityClassWithPublicConstructor:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: true
  OptionalReturnKeyword:
    active: false
  OptionalUnit:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  MagicNumber:
    active: true
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
  ModifierOrder:
    active: true
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  UseDataClass:
    active: false
  UnusedImports:
    active: true
  ExpressionBodySyntax:
    active: true
  NestedClassesVisibility:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  MatchingDeclarationName:
    active: true
  UntilInsteadOfRangeTo:
    active: true

detekt-custom-rules:
  active: true
  NoInternalImportRule:
    active: true
